### ISSUE TITLE
CMake does not work on Mac and Linux.

### ISSUE THREAD

**Issue by tokjun** [IGSIO/OpenIGTLink#17]
CMake gives the following error in commit f7c6823951c1051c64307c6093b15bb165dc7cc5:

CMake Error at /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkConfig.cmake:58 (include):
   include could not find load file:

```
 /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkTargets.cmake
```

 Call Stack (most recent call first):
   Testing/igtlutil/CMakeLists.txt:1 (find_package)

 CMake Error at /Users/junichi/igtdev/igtl/OpenIGTLink-build/UseOpenIGTLink.cmake:21 (include):
   include could not find load file:

```
 /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkTargets.cmake
```

 Call Stack (most recent call first):
   Testing/igtlutil/CMakeLists.txt:2 (include)

 CMake Error at /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkConfig.cmake:58 (include):
   include could not find load file:

```
 /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkTargets.cmake
```

 Call Stack (most recent call first):
   Testing/CMakeLists.txt:3 (find_package)

 CMake Error at /Users/junichi/igtdev/igtl/OpenIGTLink-build/UseOpenIGTLink.cmake:21 (include):
   include could not find load file:

```
 /Users/junichi/igtdev/igtl/OpenIGTLink-build/OpenIGTLinkTargets.cmake
```

 Call Stack (most recent call first):
   Testing/CMakeLists.txt:4 (include)

**Comment by adamrankin** [comment]
This has to do with longquan's in-configure configure & build of google
test.

Disabling build_testing avoids this issue.

**Comment by adamrankin** [comment]
I think we had fixed this but it may be in another repo/branch. Could you
confer with him?

**Comment by tokjun** [comment]
I think it stopped working at c9cfedb4a2462b2dc403833669d1d7fa227aceda. Maybe some of your changes in CMake is not compatible with Longquan's configuration?

**Comment by adamrankin** [comment]
Ah I see. My recommendation is to switch to a proper super build
configuration to resolve all multi stage builds.

**Comment by leochan2009** [comment]
This problem is solved in my local repository. I think it is  a good time to merge the stuff from different branches to OpenIGTLink trunk now

**Comment by leochan2009** [comment]
Hi Junichi, hi Adam,

I merged the latest commits from Adam from IGSIO/OpenIGTLink : master, and created a new branch "Version3-Development" in the openIGTLink trunk, it should fix the cmake bug and include all the nice features from Adam. 
Have a nice day!
Best Regards,
Longquan

**Comment by adamrankin** [comment]
I have merged all of the various branches into IGSIO/master and it should be all sorted.
