### ISSUE TITLE
build with OpenIGTLink_PROTOCOL_VERSION_3 = OFF

### ISSUE THREAD

**Issue by leochan2009** [IGSIO/OpenIGTLink#20]
Hi Adam,

When i try to build the library for Protocol verstion 2, it failed.
As for protocol version 2 the m_Content is also used. so i moved the m_Content outside the #if directive in MessageBass, to make this valuable available for all protocols.
Now it should work. you could merge this commit from the openIGTLink trunk into your local development :-)
Thanks

**Comment by adamrankin** [comment]
Will do!
